package seleniumTest;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.AfterAll;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.beans.factory.annotation.Autowired;
import seleniumTest.*;
import webprogramming.project.model.Manufacturer;
import webprogramming.project.repository.IngredientsRepository;
import webprogramming.project.repository.ManufacturerRepository;
import webprogramming.project.repository.PizzaRepository;
import webprogramming.project.service.ManufacturerService;
import webprogramming.project.service.impl.ManufacturerServiceImpl;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class SeleniumTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","E:\\Artan\\Fakultet\\6-Materialet e semestrit te 6\\3-Software quality and testing\\project\\Final Project\\chromedriver.exe");
        driver = new ChromeDriver();
        driver.get("http://www.google.com/");
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testadminlogincheckaddnewpizzabutton() {
        driver.get("http://localhost:9093/");
        driver.manage().window().setSize(new Dimension(1024, 728));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("veton");
        driver.findElement(By.id("password")).sendKeys("veton");
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        driver.findElement(By.linkText("Add New Pizza")).click();

        //Test if role_admin can see the add_new_pizza button
        boolean isPresent = driver.findElements(By.id("add_new_pizza_button")).size() > 0;
        assertTrue(isPresent);
    }

    @Test
    public void testuserlogin() {
        driver.get("http://localhost:9093/");
        driver.manage().window().setSize(new Dimension(1024, 728));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("artan");
        driver.findElement(By.id("password")).sendKeys("artan");
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();

        //Test if role_user can see the add_new_pizza button
        boolean isNotPresent = driver.findElements(By.id("add_new_pizza_button")).size() == 0;
        assertTrue(isNotPresent);
    }


    // no pizza test order button
    @Test
    public void testorderbuttonwithoutpizzas() {
        driver.get("http://localhost:9093/login");
        driver.manage().window().setSize(new Dimension(1024, 728));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("artan");
        driver.findElement(By.id("password")).sendKeys("artan");
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        driver.findElement(By.linkText("Order")).click();

        //Test if order button is disabled
        boolean isDisabled = driver.findElement(By.id("order_button")).isEnabled();
        assertFalse(isDisabled);
    }

//    add pizza in Order from a user
    @Test
    public void testaddpizzaremovepizzacompleteorder() {
        driver.get("http://localhost:9093/");
        driver.manage().window().setSize(new Dimension(1024, 728));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("artan");
        driver.findElement(By.id("password")).sendKeys("artan");
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();

        //Test if pizzalist in order is empty
        assertEquals(0, driver.findElements(By.id("pizzasInOrderDiv")).size());

        driver.findElement(By.linkText("Menu Pizza")).click();
        driver.findElement(By.cssSelector("div:nth-child(1) > form > #pizzasMenu .btn")).click();


        //Test if pizzalist in order has at least one element
        assertEquals(1, driver.findElements(By.id("pizzasInOrderDiv")).size());

        driver.findElement(By.linkText("Remove Pizzas")).click();
        driver.findElement(By.cssSelector(".row:nth-child(1) .btn")).click();

        //Test if pizza from pizzalist in order has been removed
        assertEquals(0, driver.findElements(By.id("pizzasInOrderDiv")).size());

        driver.findElement(By.linkText("Order")).click();
        driver.findElement(By.linkText("Add more Pizza from Menu")).click();
        driver.findElement(By.cssSelector("div:nth-child(2) .btn")).click();
        driver.findElement(By.linkText("Order")).click();
        driver.findElement(By.id("order_button")).click();
        driver.findElement(By.cssSelector(".btn-success")).click();
        driver.findElement(By.linkText("Order")).click();


    }


   
    // Test if admin can add new pizza from add_new_pizza
    @Test
    public void testadminfunctions() {
        driver.get("http://localhost:9093/");
        driver.manage().window().setSize(new Dimension(1024, 728));
        driver.findElement(By.linkText("Login")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys("veton");
        driver.findElement(By.id("password")).sendKeys("veton");
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        driver.findElement(By.linkText("Add New Pizza")).click();
        driver.findElement(By.linkText("Add new Ingredient")).click();
        driver.findElement(By.linkText("Add new Manufacturer")).click();
        driver.findElement(By.id("newManufacturerName")).click();
        driver.findElement(By.id("newManufacturerName")).sendKeys("test_man");
        driver.findElement(By.id("newManufacturerCO")).click();
        driver.findElement(By.id("newManufacturerCO")).sendKeys("UK");
        driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
        driver.findElement(By.id("newIngredientName")).click();
        driver.findElement(By.id("newIngredientName")).sendKeys("test_ing");
        driver.findElement(By.id("newIngredientPrice")).click();
        driver.findElement(By.id("newIngredientPrice")).sendKeys("50");
        driver.findElement(By.id("manId")).click();
        {
            WebElement dropdown = driver.findElement(By.id("manId"));
            dropdown.findElement(By.xpath("//option[. = 'test_man']")).click();
        }
        driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
        driver.findElement(By.id("newPizzaName")).click();
        driver.findElement(By.id("newPizzaName")).sendKeys("test_pizza");
        driver.findElement(By.id("newPizzaUrl")).click();
        driver.findElement(By.id("newPizzaUrl")).click();
        driver.findElement(By.id("newPizzaUrl")).sendKeys("https://media.istockphoto.com/photos/pizza-capricciosa-picture-id477679105");
        driver.findElement(By.id("newPizzaUrl")).click();
        driver.findElement(By.cssSelector("option:nth-child(2)")).click();
        driver.findElement(By.id("newPizzaCost")).click();
        driver.findElement(By.id("newPizzaCost")).sendKeys("150");
        driver.findElement(By.id("newPizzaSize")).click();
        driver.findElement(By.cssSelector(".btn-lg")).click();
        driver.findElement(By.linkText("Home")).click();
        driver.findElement(By.xpath("//*[@id=\"menuPizza\"]/a")).click();

        WebElement parentElement = driver.findElement(By.id("pizzasInMenu"));
        List<WebElement> allChildElements = parentElement.findElements(By.xpath("*"));

        //Test if after add the list of pizzas in menu increases by 1, from 4 to 5
        assertEquals(4, allChildElements.size());
   }

}
